### ISSUE TITLE
Pdo insted of mysqli

### ISSUE THREAD

**Issue by dnanusevski** [stefangabos/Zebra_Session#19]
Can it be adapted to work with pdo as connection.
This way i have two active connections to DB

**Comment by dnanusevski** [comment]
I have written a working code, can you please check it. I have left out 2 functions only since i do not use them.
[SessionZebraPdo.txt](https://github.com/stefangabos/Zebra_Session/files/1392696/SessionZebraPdo.txt)

**Comment by stefangabos** [comment]
Added support for PDO
