### ISSUE TITLE
Empty Session

### ISSUE THREAD

**Issue by poisons77** [stefangabos/Zebra_Session#32]
Sometimes, random or I cannot make it reproduceable, it happens the session is empty when I change page. To make it works again, I've to phisically delete the related row in the mysql Table.
I've a login, make a post call on the same page, session set correctly. Redirect to another page, session empty.
- login page - session not set
- post action, same page, session set correctly. In the DB the cell session_data is correctly updated
- redirect to index page, session empty.  In the DB the cell session_data just shows `flash_messages|a:0:{}`

What should I check to debug? Unfortunately I am not able to reproduce the problem. If I delete the row in the DB it works flawlessy.

Some more info:
- The Zebra Session is created just after loading config files and creating the mysql connection, in all files.
- If I modify the session_expire field with an older (3 days older) date, the problem remains over the time (default is 10 minutes, passed to the Zebra session constructor)

**Comment by stefangabos** [comment]
are you using the latest version?

**Comment by stefangabos** [comment]
are you using a load balancer? is something (like a browser extension) changing your browser's user agent?

**Comment by stefangabos** [comment]
are you sure you are not calling [regenerate_id](https://stefangabos.github.io/Zebra_Session/Zebra_Session/Zebra_Session.html#methodregenerate_id) on each request? also, make sure the sessions are not considered as "expired" too early - see [documentation](https://stefangabos.github.io/Zebra_Session/Zebra_Session/Zebra_Session.html#methodget_settings)

**Comment by poisons77** [comment]
sorry for the late reply.
- I'm using version 3.0 (last revision: January 28, 2020)
- I'm not using any load balancer
- I call regerate_id only once, after login

I've now forced the $session_lifetime to 600 seconds, and the issue still didn't back. I'll reopen this issue if it does. In the meantime if there's a suggestion on what to check or log to find the cause would be great.

**Comment by stefangabos** [comment]
Make sure you are calling the constructor with the defaults
```php
<?php $session = new Zebra_Session($link, 'SomeThingSomeThing');
```
also, please post the result of
```php
<?php

print_r('<pre>');
print_r($session->get_settings());

**Comment by poisons77** [comment]
This is my calling
`$session = new Zebra_Session($connection, $sessionSecurityCode);`
and this is the result of get_settings()
`Array
(
    [session.gc_maxlifetime] => 36000 seconds (600 minutes)
    [session.gc_probability] => 1
    [session.gc_divisor] => 1000
    [probability] => 0.1%
)`

**Comment by stefangabos** [comment]
everything seems fine there

**Comment by poisons77** [comment]
Ok this is reproducible.
I load a page, desktop version, the session is set and a row created in the DB. I toggle the "switch device" on chrome devTools and reload the page, mobile view now. From now on there is no way to save a session variable in the DB, nor a new session is created (the user agent changes), the only way is to manually delete the relative session row from the DB and it will create a new session on next page load. In the settings, I've $lock_to_user_agent set as default, so TRUE.

**Comment by stefangabos** [comment]
this is expected if the user agent changes - this is why i asked about this in my first comments. making it ignore the user agent should fix it but i don't recommend leaving it that way in production

**Comment by poisons77** [comment]
Yes, for some reason the user agent changed, I had no clue about what the reason, that's why I opened this topic, Thanks to your first comment I tried to force a user agent change, and then reported. Before closing the issue, should not it create a new session? The problem is that on changing the user-agent the session remain "alive", I mean the session_expire field is updated, the session_data field is emptied and remain empty, and so no more session variables can be stored. Should not it just create a new row with a new session ID? Changing the  $lock_to_user_agent setting to FALSE doesn't change the result

**Comment by stefangabos** [comment]
There was a bug where changing the user agent after initialization would make the session unusable from that point on. It should now be fixed. 

Note that when changing the user agent, the entry in the database will not be deleted but will be reused (but the value in the `hash` column will change and the session values will be deleted)

Please have a look. And again thank you for your feedback!

**Comment by poisons77** [comment]
Thanks Stefangabos for your prompt action, it seems ok now!

**Comment by poisons77** [comment]
Thanks for your prompt response Stefangabos, it seems all ok now!

**Comment by stefangabos** [comment]
Thank **you**!
