### ISSUE TITLE
Are there any reason you don't use SessionHandlerInterface class?

### ISSUE THREAD

**Issue by sayakan** [stefangabos/Zebra_Session#33]
Thank you for implementing this script!

https://www.php.net/manual/en/class.sessionhandlerinterface.php

In PHP 5 >= 5.4.0, PHP 7, it would be better to use SessionHandlerInterface class I guess.

Do you have any reasons? Thank you,

**Comment by stefangabos** [comment]
I don't remember, but the only missing thing is 
```php
class Zebra_Session implements SessionHandlerInterface
```
but other than that, Zebra_Session implements all the interfaces defined **SessionHandlerInterface** as it wouldn't work otherwise
