### ISSUE TITLE
Can't connect Zebra Session with PDO?

### ISSUE THREAD

**Issue by userc479** [stefangabos/Zebra_Session#34]
Trying to connect Zebra Session with active PDO connection and just keeps saying 'Fatal error: Zebra_Session: No MySQL connection! in C:\xampp\htdocs\assets\components\zebra_session\Zebra_Session.php on line 298' - using latest PHP and PDO rather than using Zebra Database - any help please - thank you.

**Comment by stefangabos** [comment]
are you using the latest version?

**Comment by stefangabos** [comment]
have you correctly instantiated zebra_session by passing the link to the active connection?

**Comment by userc479** [comment]
Of php yes unless you mean your libs?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stefangabos** [comment]
i mean the latest of zebra_session

**Comment by stefangabos** [comment]
try using the pdo example from the examples/ folder

**Comment by userc479** [comment]
As far as I know as the Pdo retrieve fields I want but it doesn’t seem to pick up the set variable. I will try latest version when I get back from shopping and let you know of the outcome

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by userc479** [comment]
So sorry for bothering you - it appears latest version has got it working now - apologises for that - hope you're keeping well  - thank you for keeping your projects up to date and being active and responding quickly.
