### ISSUE TITLE
transition to PDO ?

### ISSUE THREAD

**Issue by sergiokessler** [stefangabos/Zebra_Session#35]
any plans to transition this class to PDO ?

(is a very good class that that I would love to use with postgres)

**Comment by stefangabos** [comment]
it already works with PDO; read the docs for the constructor

**Comment by sergiokessler** [comment]
yup, but I mean database-agnostic, the possibility to use this class with sqlite, postgreSQL, etc
(because internally the class uses PDO for all the work)

I only see this in the constructor docs:

`
resource | &$link | An object representing the connection to a MySQL Server, as returned by calling mysqli_connect, or a PDO instance.
`

by this, **I understand** that the DB _must_ be a mysql (whether I use PDO for connecting or not)

I'm wrong ?

**Comment by stefangabos** [comment]
if a PDO instance is provided, the class uses PDO's calls internally, so whatever you instantiated PDO with should work

**Comment by sergiokessler** [comment]
Oh, glad to know, thanks !

**Comment by stefangabos** [comment]
did it work?

**Comment by sergiokessler** [comment]
sorry, didn't try with another database.
I'm using zebra_session _flawlessly_ with PDO but only mysql.

I was trying to see if we can move to postgresql and I was worried about zebra_session. 
After you reassure me that it should work, I tried to convince my boss to switch databases, but she said NO.
(I will insist in a few months however)

**Comment by papamauro** [comment]
Hi, I tried to use this library with postgres but it didn't work. I got the following error:
` PDOException: SQLSTATE[42883]: Undefined function: 7 ERROR: function get_lock(unknown, unknown) does not exist LINE 1: SELECT GET_LOCK($1, $2) ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts. in /home/.../vendor/stefangabos/zebra_session/Zebra_Session.php:740 Stack trace: #0 /home/.../vendor/stefangabos/zebra_session/Zebra_Session.php(740): PDOStatement->execute(Array) #1 /home/.../vendor/stefangabos/zebra_session/Zebra_Session.php(499): Zebra_Session->query('SELECT GET_LOCK...', '...', 60) #2 [internal function]: Zebra_Session->read('...') #3 /home/.../vendor/stefangabos/zebra_session/Zebra_Session.php(311): session_start() #4 /home/...: Zebra_Session->__construct(Object(PDO), pwd) #5 /home/.../index.php(5): framework->__construct() #6 {main}`

**Comment by stefangabos** [comment]
never tried it with postgress but it looks likr GET_LOCK is not something that postgress knows about
i'll have a look

**Comment by papamauro** [comment]
Thank you :)

**Comment by papamauro** [comment]
Any update on this?

**Comment by stefangabos** [comment]
no. i can't find a definitive explanation on how locks are implemented in postgres. would help if someone with experience would create a pull-request
