### ISSUE TITLE
If calling die(), will the session get closed/lock get released or not?

### ISSUE THREAD

**Issue by jahrralf** [stefangabos/Zebra_Session#36]
Hi, 

I am just wondering if I should register session_write_close() via session_register_shutdown(...) or if this already happens somehow... 

We are working with 60s locks and waiting for them to expire feels long. 

Thanks! 

Ralf

**Comment by stefangabos** [comment]
no, you'll have to call those yourself. that's what i am doing myself whenever i have to run cron jobs (or scripts that run for longer times). for regular users/usage should be fine the way it is

**Comment by jahrralf** [comment]
Thank you for the fast and helpful response. Might be good to mention this in the docs?
