### ISSUE TITLE
get_lock doesn't work

### ISSUE THREAD

**Issue by thepurpleblob** [stefangabos/Zebra_Session#38]
This is probably a local issue but I'm stumped.

function read($session_id) (around line 500) fails with 'Zebra_Session: Could not obtain session lock'

If I dump the contents of result it shows that it contains no data - 0 rows. No error or warning is logged. 

Any ideas?

**Comment by stefangabos** [comment]
you are probably using the same session in another tab and that is doing something that takes a long time and thus not releasing the lock.
call `session_write_close()` before engaging in something that take a long time to process so you can continue to use the same session

**Comment by thepurpleblob** [comment]
I don't think so. The application doesn't run at all and it's just me on a test server. There's nothing else running. It's failing at (I presume) session_start.

**Comment by thepurpleblob** [comment]
The problem is that rowCount() returns zero for the SELECT. I'm using Idiorm for database access and that is supplying the PDO object. I imagine it's changing some setting but I'm yet to spot what.

Some reading around casts doubt on the wisdom rowCount(). There seem to be a number of problems.

**Comment by stefangabos** [comment]
maybe the fix for #53 is related
