### ISSUE TITLE
keep session even if browser is close

### ISSUE THREAD

**Issue by TebongA** [stefangabos/Zebra_Session#40]
Hi,
I want that my session will stay even if the browser is close so I tried this code:
ini_set('session.cookie_lifetime', 1300000);
$session = new Zebra_Session($pdo, 'sessionSecCode', '', true, false, 1000);

however the moment I closed the browser.. i lost my session. is there a way for me to keep my session even if i close the browser?

**Comment by stefangabos** [comment]
This is a quirk of this library :) 
I will fix it in the next release, I promise!

For now, go to line 241 and put your value there. You could set it to something like `315360000` (10 years)
