### ISSUE TITLE
session_start gives an unkown error 

### ISSUE THREAD

**Issue by kvvaradha** [stefangabos/Zebra_Session#44]
As i am trying to integrate your session class on my one of a PHP project. Which i am unable to use your 

`if($session_start){
session_start();
} `

After this code, nothing works, I don't understand the reason i followed like what you are instructed here .

**Comment by stefangabos** [comment]
enable error reporting and you'll see what's wrong
set these at the top of your script
```php
ini_set('display_errors', 1);
error_reporting(E_ALL);
```

**Comment by kvvaradha** [comment]
Thanks for the prompt response dude, its because of the database name i input wrong.
