### ISSUE TITLE
Divide by zero error when calling get_settings()

### ISSUE THREAD

**Issue by alexp-uk** [stefangabos/Zebra_Session#48]
When calling get_settings(), line 477:
'probability' =>  (int)$gc_probability / (int)$gc_divisor * 100 . '%',

Triggers a divide by zero error when running on a host that has 'session.gc_divisor' set to 0.

Thanks so much for this useful tool by the way! :)

**Comment by stefangabos** [comment]
Thanks for the heads up. I pushed out a fix and will publish a release soon
