### ISSUE TITLE
$session->set_flashdata() not working

### ISSUE THREAD

**Issue by 09173732546** [stefangabos/Zebra_Session#51]
Hi, can you confirm if this is not working,

Files:
1. ini.php with new Zebra_Session($link, $code);
2. index.php with vardump($_SESSION);
3. logout.php that will delete sessions and with $session->set_flashdata('myvar', 'myval');

Step:
1. access /logout.php (cookies and session are deleted via setcookie() and $session-stop() and execute $session->set_flashdata('myvar', 'myval') and redirect to index.php 
3. index php var_dump($_SESSION) does not show `myvar` variable with or without adding session_start() prior the set_flashdata()

both index and logout have require_once 'ini.php';

**Comment by stefangabos** [comment]
There is no session after calling `$session->stop()` so the behaviour is the expected one

**Comment by 09173732546** [comment]
thanks, i thought i can just use session_start() from logout.php

**Comment by stefangabos** [comment]
i recommend using [regenerate_id](https://stefangabos.github.io/Zebra_Session/Zebra_Session/Zebra_Session.html#methodregenerate_id) instead of stopping the session and everything will then work as you'd expect
