### ISSUE TITLE
Maybe a $lock_to_ip extension

### ISSUE THREAD

**Issue by Lightwight** [stefangabos/Zebra_Session#7]
First of all: What an awesome Class. I am using it for my project and i am very satisfied with it.
Next: Sorry for my bad english. I am not good at all :)

Now the idea: As in the class description described u should use $lock_to_ip with caution because of the proxie issue or dynamic IP changes which i agree. So it would be nice, if we can pass a parameter [string] to the constructor for extending the hash.

In my scenario i would do a client side fingerprint and send it back to the server (via ajax) for passing it to the ZebraSession constuctor. Then i would be able to determine the session with its client more precise. Is it possible to implement it?

**Comment by stefangabos** [comment]
`4.1.0` fixed this
